version: "3"

services:
  ctfd:
    image: whitehats/bts_ctfd:${CTFD_IMG_VERSION} 
    restart: always
    expose:
      - ${CTF_PORT}
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://${MYSQL_ROOT_PASSWORD}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      - REDIS_URL=redis://cache:${REDIS_PORT}
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=${CTF_PORT}
      - SERVICE_PORTS=${CTF_PORT}
    volumes:
      - ./data/CTFd/logs:/var/log/CTFd
      - ./data/CTFd/uploads:/var/uploads
    depends_on:
      - db
    networks:
        default:
        internal:

  db:
    image: mariadb:${MARIADB_IMG_VERSION}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: chown -R mysql:mysql /var/lib/mysql;
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  # cache server based on redis
  cache:
    image: redis:${REDIS_IMG_VERSION}
    restart: always
    volumes:
    - ./data/redis:/data
    networks:
        internal:

  # load balancer based on nginx
  lb:
    image: jwilder/nginx-proxy:${NGINX_PROXY_VERSION}
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - ctfd
    expose:
      - ${LB_PORT}
    networks: 
      default:

  nginx:
    image: nginx:${NGINX_VERSION}
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_HOST_PORT}:${NGINX_PORT} 
    links:
      - lb
    networks: 
      default:


networks:
    default:
      external:
        name: monitoring-shared-network
    internal:
        internal: true