version: '2.1'

networks:
  monitor-net:
    internal: true
  default:
    external:
      name: monitoring-shared-network

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - ${PROMETHEUS_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - ${NODE_EXPORTER_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:${CADVISOR_VERSION}
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - ${CADVISOR_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - ${GRAFANA_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway:${PUSHGATEWAY_VERSION}
    restart: unless-stopped
    expose:
      - ${PUSHGATEWAY_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:${NGINX_PROM_EXPORTER_VERSION}
    restart: unless-stopped
    expose:
      - ${NGINX_PROM_EXPORTER_PORT}
    ports:
      - ${NGINX_PROM_EXPORTER_PORT}:${NGINX_PROM_EXPORTER_PORT}
    networks:
      - monitor-net
      - default
    environment: 
      - SCRAPE_URI=http://nginx:80/stub_status
      - NGINX_RETRIES=10
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: stefanprodan/caddy
    expose:
      - ${GRAFANA_PORT}
      - ${PROMETHEUS_PORT}
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    networks:
      - default
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"