{
 "title": "CTFd Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CTFd containers online",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{name=~\".*ctfd.*\"}[20s]))",
     "legendFormat": "Containers online"
    }
   ]
  },
  {
   "title": "CTFd 1st Container Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{name=~\".*ctfd_1.*\"}[20s]))"
    }
   ]
  },
  {
   "title": "CTFd 2nd Container Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{name=~\".*ctfd_2.*\"}[20s]))"
    }
   ]
  },
  {
   "title": "CTFd 3rd Container Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{name=~\".*ctfd_3.*\"}[20s]))"
    }
   ]
  },
  {
   "title": "Network packets transmited by CTFd containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_packets_total{name=~\".*ctf.*\"}[20s]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network packets transmited by CTFd containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_packets_dropped_total{name=~\".*ctf.*\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}